// backend/src/common/constants/notification.constants.ts
export const NOTIFICATION_TYPES = {
  SHIFT_ASSIGNED: 'SHIFT_ASSIGNED',
  SHIFT_CHANGED: 'SHIFT_CHANGED',
  SHIFT_CANCELLED: 'SHIFT_CANCELLED',
  SHIFT_PUBLISHED: 'SHIFT_PUBLISHED',
  SWAP_REQUESTED: 'SWAP_REQUESTED',
  SWAP_ACCEPTED: 'SWAP_ACCEPTED',
  SWAP_DECLINED: 'SWAP_DECLINED',
  SWAP_APPROVED: 'SWAP_APPROVED',
  SWAP_REJECTED: 'SWAP_REJECTED',
  DROP_REQUESTED: 'DROP_REQUESTED',
  DROP_ACCEPTED: 'DROP_ACCEPTED',
  OVERTIME_WARNING: 'OVERTIME_WARNING',
  CONSECUTIVE_DAY_WARNING: 'CONSECUTIVE_DAY_WARNING',
  SCHEDULE_PUBLISHED: 'SCHEDULE_PUBLISHED',
  AVAILABILITY_CHANGED: 'AVAILABILITY_CHANGED',
  CERTIFICATION_EXPIRING: 'CERTIFICATION_EXPIRING',
  LOCATION_TRANSFER: 'LOCATION_TRANSFER',
} as const;

export type NOTIFICATION_TYPES = typeof NOTIFICATION_TYPES[keyof typeof NOTIFICATION_TYPES];

export const NOTIFICATION_PRIORITY = {
  LOW: 0,
  NORMAL: 1,
  HIGH: 2,
  URGENT: 3,
} as const;

export type NotificationPriority = typeof NOTIFICATION_PRIORITY[keyof typeof NOTIFICATION_PRIORITY];

export const DEFAULT_NOTIFICATION_PREFS = {
  inApp: true,
  email: false,
  push: false,
  digest: false,
};